CREATE TABLE pessoa(
  id SERIAL PRIMARY KEY NOT NULL UNIQUE,
  nome VARCHAR(100) NOT NULL,
  ativo boolean NOT NULL,
  logradouro VARCHAR(100) NOT NULL,
  numero VARCHAR(100) NOT NULL,
  complemento VARCHAR(100),
  bairro VARCHAR(50) NOT NULL,
  cep VARCHAR(30) NOT NULL,
  cidade VARCHAR(100) NOT NULL,
  estado VARCHAR(40) NOT NULL
);

